spring:
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
    url: ${MS_MINIO_URL}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
minio:
  url: ${MINIO_URL}
  bucket: ${MINIO_BUCKET}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  image-folder: ${MINIO_IMAGE_FOLDER}
  file-folder: ${MINIO_FILE_FOLDER}

file:
  upload:
    acceptableFileExtensions: pdf,jpg,png,jpeg
    acceptableImageExtensions: jpg,png,jpeg


server:
  port: 8056
  address:

  secure: http
  file-controller-path: ${MINIO_FILE_CONTROLLER_PATH}


client:
  users:
    int:
      url: ${CLINET_MS_USER_URL}